"""Add jointable UsersInvestors

Revision ID: 1332389a02ea
Revises: ae414e1170f0
Create Date: 2017-06-01 22:17:05.772767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1332389a02ea'
down_revision = 'ae414e1170f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_investors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_investors')
    # ### end Alembic commands ###
