"""Add market to startups model

Revision ID: 7b56479a3b10
Revises: 8cff978f35eb
Create Date: 2017-05-31 16:33:07.075357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b56479a3b10'
down_revision = '8cff978f35eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('market', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('startups', 'market')
    # ### end Alembic commands ###
