"""Delete fullname from UserForm

Revision ID: 85e040982066
Revises: 0f6fcaa5408c
Create Date: 2017-05-30 10:45:17.076738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e040982066'
down_revision = '0f6fcaa5408c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
