"""Add Market, InvestorsMarkets

Revision ID: a1bfc2924410
Revises: 7b56479a3b10
Create Date: 2017-06-01 14:07:55.365932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bfc2924410'
down_revision = '7b56479a3b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investors_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investors_markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
